# -*- coding: utf-8 -*-
"""oss_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XUfSq67KAIOtDai0RfvuqgoeSFr6Qfn
"""

while True:
    coin = int(input("돈을 넣으세요. -> "))
    sell = int(input("1.오렌지주스 : 1500원, 2.커피 : 1500원, 3.콜라 : 1800원, 4.카페모카 : 2500원  --> "))
    if sell < 1 or sell > 4:
        print("없는 메뉴")
        continue

    if sell == 1:
        if coin < 1500:
            print("잔액부족")
            continue
        a = coin - 1500
        print(f"잔액->{a}")
        break
    elif sell == 2:
        if coin < 1500:
            print("잔액부족")
            continue
        a = coin - 1500
        print(f"잔액->{a}")
        break
    elif sell == 3:
        if coin < 1800:
            print("잔액부족")
            continue
        a = coin - 1800
        print(f"잔액->{a}")
        break
    elif sell == 4:
        if coin < 2500:
            print("잔액부족")
            continue
        a = coin - 2500
        print(f"잔액->{a}")
        break